In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 1. Version of numpy and the configuration
print(np.__version__)
print("\n")
print(np.show_config())

1.21.6


blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2,AVX512F,AVX512CD,AVX512_SKX,A

In [3]:
# 2. null vector of size 10
null = np.zeros(10)
null

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
# 3. memory of the array
print(null.itemsize * null.size)

80


 4. We can get the help of the numpy documentation from the command line by using  ? funtion beside the function for which the help is required

In [5]:
# 5. null vectors with 5 th position as 1
null5 = np.zeros(10)
null5[4] = 1
null5

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [6]:
# 6. vector with values ranging from 10 to 49
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
#7. reversing a vector
vector = np.flip(vector)
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [8]:
#8. 3X3 matrix
mat = np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
#9. indices of the matrix
ind = [1,2,0,0,4,0]
print(np.nonzero(ind))

(array([0, 1, 4], dtype=int64),)


In [10]:
#10. identity matrix
ide = np.identity(3)
ide

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#11. random matrix

rand = np.random.random((3,3,3))
rand

array([[[0.41409944, 0.14775529, 0.23693752],
        [0.20534789, 0.00839393, 0.24051708],
        [0.46687908, 0.37877614, 0.9313943 ]],

       [[0.59620642, 0.72267193, 0.07560994],
        [0.48680599, 0.47870145, 0.91240155],
        [0.71383644, 0.45162587, 0.14122438]],

       [[0.79293693, 0.72870481, 0.08038921],
        [0.57556447, 0.78436805, 0.50764508],
        [0.66790056, 0.37952421, 0.88103418]]])

In [44]:
#12. 10x10 array with random values
matrix = np.random.rand(10,10)
print(np.max(matrix))
print(" ")
np.min(matrix)

0.9967303209009339
 


0.006240956256607699

In [20]:
#13.  random vector of size 30 
vec = np.random.random(30)
print(np.mean(vec))

0.5234775126904059


In [23]:
#14. 2d array with 1 on the border and 0 inside
mat = np.ones(100).reshape(10,10)
mat[1:-1, 1:-1]=0
mat

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [25]:
# 15. add a border (filled with 0's) around an existing array
for i in range(len(mat)):
    for j in range(len(mat)):
        if mat[i][j] ==1:
            mat[i][j]=0
mat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
# 16.  result of the following expressions
 # a. 0 * np.nan
0*np.nan

nan

In [29]:
# b. np.nan == np.nan
np.nan == np.nan

False

In [30]:
# c.np.inf > np.nan
np.inf > np.nan

False

In [31]:
# d.np.nan - np.nan
np.nan - np.nan

nan

In [32]:
# e. np.nan in set([np.nan])
np.nan in set([np.nan])

True

In [33]:
# f. 0.3 == 3 * 0.1
0.3 == 3 * 0.1

False

In [56]:
# 17. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
rix= np.diag(1+np.arange(6), k=-1)
print(rix)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]]


In [67]:
#18.Create a 8x8 matrix and fill it with a checkerboard pattern
check = np.zeros((8,8))
check[1::2,::2]=1
check[::2,1::2]=1
check

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [79]:
#19.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
sixarray = np.array(np.random.rand(336).reshape(6,7,8))
sixarray

array([[[0.45566628, 0.88882252, 0.51936687, 0.72044937, 0.1104831 ,
         0.1903745 , 0.95873382, 0.2786232 ],
        [0.58502411, 0.98958088, 0.39600531, 0.38584572, 0.95147307,
         0.30968725, 0.60566873, 0.24124734],
        [0.19723637, 0.66342828, 0.04270905, 0.13428047, 0.28181377,
         0.05545509, 0.20735396, 0.81231556],
        [0.96093423, 0.45229221, 0.45810482, 0.42422513, 0.86500201,
         0.6253399 , 0.72370771, 0.20228019],
        [0.22053643, 0.20902698, 0.4461076 , 0.69402698, 0.57412136,
         0.77400279, 0.98292956, 0.61107299],
        [0.11414344, 0.72203349, 0.89757523, 0.83627637, 0.89763088,
         0.01969884, 0.7826758 , 0.21522211],
        [0.41502502, 0.53131132, 0.78662028, 0.27975241, 0.46125253,
         0.63080122, 0.04079365, 0.44871024]],

       [[0.53934849, 0.63903862, 0.20238854, 0.99232797, 0.90204475,
         0.18682163, 0.23599861, 0.83904774],
        [0.10637866, 0.29257616, 0.77814595, 0.38571974, 0.42972539,
         

In [82]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [83]:
print(sixarray[1,5,4])

0.5035907161400301


# 20. Give your views regarding numpy vs pandas in python 

1. The Numpy is the library is mostly used to handle the numerical datas such as arrays whereas the Pandas library is used to handle DataFrames.

2. Numpy mostly handels arrays and Pandas can handle data in the form of DataFrames and Series

3. Pandas has more performance than numpy 

4. We can visualize the data with pandas whereas in numpy we can extend it upto n-dimensional arrays