In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.8.0


In [3]:
scalar = tf.constant(7)

In [4]:
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
vector = tf.constant([10,8])

In [6]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8])>

In [7]:
scalar.ndim

0

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[10,9],
                    [11,12]])

In [10]:
matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

In [12]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [13]:
tensor.ndim

3

In [14]:
changeble_tensor = tf.Variable([10,7])

In [15]:
unchangeble_tensor = tf.constant([11,12])

In [16]:
changeble_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [17]:
changeble_tensor[1].assign(8)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10,  8])>

In [18]:
changeble_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [19]:
unchangeble_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [20]:
#unchangeble_tensor[0].assign(1)

In [21]:
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3, 2))

In [22]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape=(3,2))

In [23]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [25]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [26]:
not_shuffled = tf.constant([[10,7],
                           [11,8],
                           [12,9]])

In [27]:
shuffled = tf.random.shuffle(not_shuffled, seed=50)

In [28]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11,  8],
       [12,  9],
       [10,  7]])>

In [29]:
tf.ones(shape=(10,4))

<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [31]:
import numpy as np

In [32]:
arr = np.arange(1,25)

In [33]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [34]:
A = tf.constant(arr, shape=(2,4,3))

In [35]:
A

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [36]:
B = tf.constant(A)

In [37]:
B

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])>

In [38]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [39]:
print("The Datatype of the Rank 4 Tensor", rank_4_tensor.dtype)
print("The Dimension of the Rank 4 Tensor", rank_4_tensor.ndim)
print("The Shape of the Tensor", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy())

The Datatype of the Rank 4 Tensor <dtype: 'float32'>
The Dimension of the Rank 4 Tensor 4
The Shape of the Tensor (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [40]:
rank_4_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [41]:
rank_2_tensor = tf.constant([[10,9],
                            [15,16]])

In [42]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 16])>

In [43]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [44]:
rank_2_tensor, rank_3_tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  9],
        [15, 16]])>,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 9]],
 
        [[15],
         [16]]])>)

In [45]:
tf.expand_dims(rank_2_tensor, axis=-1) 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 9]],

       [[15],
        [16]]])>

In [46]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [47]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [48]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [49]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [50]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [51]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


In [52]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [53]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [54]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

In [55]:
y = Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])

In [56]:
tf.reshape(X, shape=(2,3))
tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [57]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [58]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [59]:
tf.transpose(y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]])>

In [60]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [61]:
tf.matmul(a=X, b=Y, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [62]:
tf.tensordot(tf.transpose(X), y, axes=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [63]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [64]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [65]:
print("Normal Y:")
print(y, "\n") # "\n" for newline

print("Y reshaped to (2, 3):")
print(tf.reshape(y, (2, 3)), "\n")

print("Y transposed:")
print(tf.transpose(y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2, 3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [66]:
B = tf.constant([9,10])

In [67]:
B.dtype

tf.int32

In [68]:
D = tf.cast(B, dtype=tf.float32)

In [69]:
D.dtype

tf.float32

In [70]:
d = tf.constant([-100,500])

In [71]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([100, 500])>

In [72]:
sample = tf.constant(np.random.randint(0,100,50))

In [73]:
sample

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([72,  5, 89, 24, 93, 82, 66, 14, 55,  3, 37, 35, 89, 83, 12, 80, 61,
       41, 87,  9, 97, 44, 10, 17,  5,  1, 29, 86, 31, 88, 69, 61, 67,  2,
       24, 62, 35, 74, 94, 89, 66, 64, 32, 73, 46, 15, 18, 11, 78, 85])>

In [74]:
tf.reduce_min(sample)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [75]:
tf.reduce_max(sample)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

In [76]:
tf.reduce_mean(sample)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [77]:
tf.reduce_sum(sample)

<tf.Tensor: shape=(), dtype=int32, numpy=2510>

In [78]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.1213854 , 0.86860874, 0.92103294, 0.26283169, 0.80644262,
       0.89186819, 0.73624048, 0.6834698 , 0.18477851, 0.36000798,
       0.75351866, 0.40175166, 0.06101968, 0.77745866, 0.42509036,
       0.25600498, 0.54489856, 0.46874709, 0.66051023, 0.17867527,
       0.26519148, 0.59493815, 0.82601977, 0.5848953 , 0.55005136,
       0.99641638, 0.64778353, 0.70949029, 0.9628166 , 0.43669415,
       0.89231174, 0.10963188, 0.79282203, 0.30253062, 0.30891783,
       0.38116348, 0.94819279, 0.22738132, 0.90734113, 0.0813349 ,
       0.95263577, 0.46782976, 0.094402  , 0.98538996, 0.05589997,
       0.90300405, 0.61353122, 0.01335237, 0.62088359, 0.12440971])>

In [79]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [80]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

In [81]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9964163832592631>

In [82]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.013352372442970495>

In [83]:
G = tf.constant(np.random.randint(0,100, 50), shape=(1,1,1,50))

In [84]:
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=int32, numpy=
array([[[[55, 74, 55, 92, 57, 59, 70, 86, 61, 57, 74, 30, 26, 92, 61,
           2, 65, 66, 15, 56, 45, 92, 94, 34, 34, 23, 14, 73,  2, 10,
          25, 55, 28, 57, 88, 26, 12, 90, 87, 73, 56, 36, 62, 81, 37,
          35, 98, 84, 88, 81]]]])>

In [85]:
G_Squeezed = tf.squeeze(G)

In [86]:
G_Squeezed

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([55, 74, 55, 92, 57, 59, 70, 86, 61, 57, 74, 30, 26, 92, 61,  2, 65,
       66, 15, 56, 45, 92, 94, 34, 34, 23, 14, 73,  2, 10, 25, 55, 28, 57,
       88, 26, 12, 90, 87, 73, 56, 36, 62, 81, 37, 35, 98, 84, 88, 81])>

In [87]:
lists = [1,2,3,4,5]

one_hot = tf.one_hot(lists, depth=10)

In [88]:
one_hot

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)>

In [89]:
tf.one_hot(lists, depth=5, on_value="We're live!", off_value="Offline")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Offline', b"We're live!", b'Offline', b'Offline', b'Offline'],
       [b'Offline', b'Offline', b"We're live!", b'Offline', b'Offline'],
       [b'Offline', b'Offline', b'Offline', b"We're live!", b'Offline'],
       [b'Offline', b'Offline', b'Offline', b'Offline', b"We're live!"],
       [b'Offline', b'Offline', b'Offline', b'Offline', b'Offline']],
      dtype=object)>

In [90]:
H = tf.constant(np.arange(0,10))
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [91]:
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [92]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.        , 0.99999994, 1.4142134 , 1.7320508 , 1.9999999 ,
       2.236068  , 2.4494896 , 2.6457512 , 2.828427  , 3.        ],
      dtype=float32)>

In [93]:
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([     -inf, 0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 ,
       1.7917595, 1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [94]:
I = tf.Variable(np.arange(0,11))
I

<tf.Variable 'Variable:0' shape=(11,) dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [95]:
I.assign([0,1,2,3,4,5,6,7,8,9,10])

<tf.Variable 'UnreadVariable' shape=(11,) dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [96]:
I.assign_add([10, 10, 10, 10, 10,10,10,10,10,10,10])

<tf.Variable 'UnreadVariable' shape=(11,) dtype=int32, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])>

In [97]:
I

<tf.Variable 'Variable:0' shape=(11,) dtype=int32, numpy=array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])>

In [98]:
J = tf.constant(np.array([3.,7.,10.]))

In [99]:
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [100]:
J.numpy()

array([ 3.,  7., 10.])

In [101]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([4.,8.,11.])

In [102]:
numpy_J.dtype

tf.float64

In [103]:
tensor_J.dtype

tf.float32

In [104]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [105]:
import tensorflow as tf
print(tf.config.list_physical_devices('GPU'))

[]


In [106]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.
