In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
import tensorflow as tf

In [3]:
scalar = tf.constant(7)

In [4]:
scalar.ndim

0

In [5]:
vector = tf.constant([1,2])

In [6]:
vector.ndim

1

In [7]:
matrix  = tf.constant([[3,4],
                      [5,6]])

In [8]:
matrix.ndim

2

In [9]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

TensorShape([3, 2, 3])

In [12]:
tensor.ref

<bound method Tensor.ref of <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>>

In [13]:
t_1 = tf.random.Generator.from_seed(42)
t_1 = t_1.normal(shape=(5,300))
t_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
        -1.0722276 , -0.00586287],
       [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
         1.155565  , -0.10707551],
       [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
         1.216793  , -1.24293   ],
       [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
        -0.73970354,  0.0177109 ],
       [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
         0.5656089 ,  0.18439196]], dtype=float32)>

In [14]:
t_2 = tf.random.Generator.from_seed(42)
t_2 = t_2.uniform(shape=(5,300))
t_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, ..., 0.5816356 , 0.5627874 ,
        0.7491298 ],
       [0.6438937 , 0.6938418 , 0.04408407, ..., 0.04825139, 0.5099728 ,
        0.26470542],
       [0.21373153, 0.6683699 , 0.78474844, ..., 0.19658887, 0.22030771,
        0.3766911 ],
       [0.68190825, 0.29304636, 0.5415933 , ..., 0.37111604, 0.76053166,
        0.7538099 ],
       [0.8011551 , 0.48830473, 0.13867617, ..., 0.20301867, 0.8378159 ,
        0.19984365]], dtype=float32)>

In [15]:
tf.matmul(tf.transpose(t_1), t_2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[-0.846868  , -1.9195682 , -1.1187468 , ..., -0.4605882 ,
        -0.52977884, -0.7310309 ],
       [-1.1358638 , -1.2443552 , -0.94049245, ..., -0.44656953,
        -1.1280476 , -0.77085674],
       [-2.7182858 , -2.5249243 , -0.21981946, ..., -0.31204015,
        -2.43268   , -0.6972771 ],
       ...,
       [-1.1786896 , -0.6552377 , -0.7462503 , ..., -0.8955323 ,
        -1.0734441 , -1.3772823 ],
       [ 0.14939055,  0.88571745,  0.19865929, ..., -0.48836678,
         0.1652476 , -0.48356074],
       [-0.17918815, -0.8141137 , -0.94759667, ..., -0.208915  ,
        -0.16377601, -0.450736  ]], dtype=float32)>

In [16]:
tf.tensordot(t_1,tf.transpose(t_2), axes=True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -9.258241 , -15.189949 , -14.499577 , -15.634086 ,  -7.9322157],
       [ -7.2313747,  -3.4149356,  -4.73195  ,  -9.376359 , -11.401805 ],
       [  5.921939 ,  -4.117131 ,   7.3674498,   5.767094 ,   4.8917212],
       [ -4.5555515,  -3.6235137,  -6.238871 ,  -5.3141756, -10.262813 ],
       [  6.274344 ,   3.9981017,   1.3461664,   9.228268 ,   2.086178 ]],
      dtype=float32)>

In [17]:
tensor_6 = tf.random.Generator.from_seed(42)
tensor_6 = tensor_6.uniform(shape=(224, 224, 3))
tensor_6

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7493447 , 0.73561966, 0.45230794],
        [0.49039817, 0.1889317 , 0.52027524],
        [0.8736881 , 0.46921718, 0.63932586],
        ...,
        [0.8035464 , 0.8265822 , 0.84540355],
        [0.16108847, 0.48667014, 0.6170937 ],
        [0.22355545, 0.93454087, 0.5319209 ]],

       [[0.7508148 , 0.46019256, 0.14229465],
        [0.10500956, 0.72874916, 0.89662087],
        [0.85220826, 0.76973283, 0.11408448],
        ...,
        [0.38387823, 0.72712064, 0.7561674 ],
        [0.70352066, 0.22680473, 0.24423313],
        [0.39240444, 0.32533252, 0.39407527]],

       [[0.74291146, 0.54543686, 0.32094967],
        [0.6671035 , 0.8900143 , 0.64271927],
        [0.5317905 , 0.21345353, 0.71189904],
        ...,
        [0.53968227, 0.7233304 , 0.7900686 ],
        [0.99334645, 0.857829  , 0.67977047],
        [0.8087704 , 0.06597769, 0.62171316]],

       ...,

       [[0.84861326, 0.6271888 , 0.7023717 ],
        [0.46

In [18]:
tf.reduce_min(tensor_6)

<tf.Tensor: shape=(), dtype=float32, numpy=4.053116e-06>

In [19]:
tf.reduce_max(tensor_6)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99998736>

In [20]:
tensor_8 = tf.random.Generator.from_seed(42)
tensor_8 = tensor_8.normal(shape = (1,224,224,3))
tensor_8

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646, -0.7535805 ],
         ...,
         [ 0.07099114, -0.5095768 ,  0.3482001 ],
         [ 0.15985982, -1.9042184 ,  0.9690504 ],
         [ 0.16251186, -0.07330752, -0.360591  ]],

        [[ 0.18739441, -0.73353654,  1.2104433 ],
         [ 1.5603006 , -0.48115277,  0.6335167 ],
         [-0.5612103 ,  0.06994031,  1.6807095 ],
         ...,
         [-1.9460293 , -0.7977275 ,  0.03092833],
         [ 0.8297488 ,  0.12179119,  1.0506107 ],
         [-1.3097638 ,  0.92536974, -1.1787732 ]],

        [[-0.21711822, -0.73974085, -1.3077081 ],
         [-0.7502274 , -0.37715855, -0.30130875],
         [ 1.0943383 ,  0.255803  ,  0.8011465 ],
         ...,
         [-0.32833767, -0.7794747 ,  0.20049338],
         [-0.09002841,  0.07243238, -0.81940895],
         [ 0.3171264 , -1.6143695 , -1.6824651

In [21]:
tensor_8 = tf.squeeze(tensor_8)

In [22]:
tensor_8.shape

TensorShape([224, 224, 3])

In [23]:
tensor_9 = tf.constant(np.random.randint(0,50,10))

In [24]:
tensor_9

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([49, 16,  4, 10, 47,  4, 45,  8, 45, 41])>

In [25]:
print(tf.reduce_max(tf.argmax(tensor_9)))

tf.Tensor(0, shape=(), dtype=int64)


In [26]:
tf.one_hot(tensor_9, depth=40)

<tf.Tensor: shape=(10, 40), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1